=== GoldGamesTKD/Legacy-Interlude/gameserver/data/stats/player/gain_level/gain_level.dtd
<!ELEMENT list (gain)*>
<!ELEMENT gain (level)*>
<!ATTLIST gain
        class_id CDATA #REQUIRED>
<!ELEMENT level (#PCDATA)>
<!ATTLIST level
        cp CDATA #REQUIRED
        hp CDATA #REQUIRED
        mp CDATA #REQUIRED
        val CDATA #REQUIRED>

=== GoldGamesTKD/Legacy-Interlude/gameserver/data/stats/player/gain_level/[36] abyss_walker.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "gain_level.dtd">
<list>
    <gain class_id="36">
        <level val="1" hp="94.0" mp="30.0" cp="37.6"/>
        <level val="2" hp="107.65" mp="35.46" cp="43.06"/>
        <level val="3" hp="121.45" mp="40.98" cp="48.58"/>
        <level val="4" hp="135.4" mp="46.56" cp="54.16"/>
        <level val="5" hp="149.5" mp="52.2" cp="59.8"/>
        <level val="6" hp="163.75" mp="57.9" cp="65.5"/>
        <level val="7" hp="178.15" mp="63.66" cp="71.26"/>
        <level val="8" hp="192.7" mp="69.48" cp="77.08"/>
        <level val="9" hp="207.4" mp="75.36" cp="82.96"/>
        <level val="10" hp="222.25" mp="81.3" cp="88.9"/>
        <level val="11" hp="237.25" mp="87.3" cp="94.9"/>
        <level val="12" hp="252.4" mp="93.36" cp="100.96"/>
        <level val="13" hp="267.7" mp="99.48" cp="107.08"/>
        <level val="14" hp="283.15" mp="105.66" cp="113.26"/>
        <level val="15" hp="298.75" mp="111.9" cp="119.5"/>
        <level val="16" hp="314.5" mp="118.2" cp="125.8"/>
        <level val="17" hp="330.4" mp="124.56" cp="132.16"/>
        <level val="18" hp="346.45" mp="130.98" cp="138.58"/>
        <level val="19" hp="362.65" mp="137.46" cp="145.06"/>
        <level val="20" hp="379.0" mp="144.0" cp="151.6"/>
        <level val="21" hp="412.0" mp="153.9" cp="164.8"/>
        <level val="22" hp="445.3" mp="163.89" cp="178.12"/>
        <level val="23" hp="478.9" mp="173.97" cp="191.56"/>
        <level val="24" hp="512.8" mp="184.14" cp="205.12"/>
        <level val="25" hp="547.0" mp="194.4" cp="218.8"/>
        <level val="26" hp="581.5" mp="204.75" cp="232.6"/>
        <level val="27" hp="616.3" mp="215.19" cp="246.52"/>
        <level val="28" hp="651.4" mp="225.72" cp="260.56"/>
        <level val="29" hp="686.8" mp="236.34" cp="274.72"/>
        <level val="30" hp="722.5" mp="247.05" cp="289"/>
        <level val="31" hp="758.5" mp="257.85" cp="303.4"/>
        <level val="32" hp="794.8" mp="268.74" cp="317.92"/>
        <level val="33" hp="831.4" mp="279.72" cp="332.56"/>
        <level val="34" hp="868.3" mp="290.79" cp="347.32"/>
        <level val="35" hp="905.5" mp="301.95" cp="362.2"/>
        <level val="36" hp="943.0" mp="313.2" cp="377.2"/>
        <level val="37" hp="980.8" mp="324.54" cp="392.32"/>
        <level val="38" hp="1018.9" mp="335.97" cp="407.56"/>
        <level val="39" hp="1057.3" mp="347.49" cp="422.92"/>
        <level val="40" hp="1096.0" mp="359.1" cp="438.4"/>
        <level val="41" hp="1145.4" mp="378.6" cp="458.16"/>
        <level val="42" hp="1195.18" mp="398.25" cp="478.072"/>
        <level val="43" hp="1245.34" mp="418.05" cp="498.136"/>
        <level val="44" hp="1295.88" mp="438.0" cp="518.352"/>
        <level val="45" hp="1346.8" mp="458.1" cp="538.72"/>
        <level val="46" hp="1398.1" mp="478.35" cp="559.24"/>
        <level val="47" hp="1449.78" mp="498.75" cp="579.912"/>
        <level val="48" hp="1501.84" mp="519.3" cp="600.736"/>
        <level val="49" hp="1554.28" mp="540.0" cp="621.712"/>
        <level val="50" hp="1607.1" mp="560.85" cp="642.84"/>
        <level val="51" hp="1660.3" mp="581.85" cp="664.12"/>
        <level val="52" hp="1713.88" mp="603.0" cp="685.552"/>
        <level val="53" hp="1767.84" mp="624.3" cp="707.136"/>
        <level val="54" hp="1822.18" mp="645.75" cp="728.872"/>
        <level val="55" hp="1876.9" mp="667.35" cp="750.76"/>
        <level val="56" hp="1932.0" mp="689.1" cp="772.8"/>
        <level val="57" hp="1987.48" mp="711.0" cp="794.992"/>
        <level val="58" hp="2043.34" mp="733.05" cp="817.336"/>
        <level val="59" hp="2099.58" mp="755.25" cp="839.832"/>
        <level val="60" hp="2156.2" mp="777.6" cp="862.48"/>
        <level val="61" hp="2213.2" mp="800.1" cp="885.28"/>
        <level val="62" hp="2270.58" mp="822.75" cp="908.232"/>
        <level val="63" hp="2328.34" mp="845.55" cp="931.336"/>
        <level val="64" hp="2386.48" mp="868.5" cp="954.592"/>
        <level val="65" hp="2445.0" mp="891.6" cp="978"/>
        <level val="66" hp="2503.9" mp="914.85" cp="1001.56"/>
        <level val="67" hp="2563.18" mp="938.25" cp="1025.27"/>
        <level val="68" hp="2622.84" mp="961.8" cp="1049.14"/>
        <level val="69" hp="2682.88" mp="985.5" cp="1073.15"/>
        <level val="70" hp="2743.3" mp="1009.35" cp="1097.32"/>
        <level val="71" hp="2804.1" mp="1033.35" cp="1121.64"/>
        <level val="72" hp="2865.28" mp="1057.5" cp="1146.11"/>
        <level val="73" hp="2926.84" mp="1081.8" cp="1170.74"/>
        <level val="74" hp="2988.78" mp="1106.25" cp="1195.51"/>
        <level val="75" hp="3051.1" mp="1130.85" cp="1220.44"/>
        <level val="76" hp="3113.8" mp="1155.6" cp="1245.52"/>
        <level val="77" hp="3176.88" mp="1180.5" cp="1270.75"/>
        <level val="78" hp="3240.34" mp="1205.55" cp="1296.14"/>
        <level val="79" hp="3304.18" mp="1230.75" cp="1321.67"/>
        <level val="80" hp="3368.4" mp="1256.1" cp="1347.36"/>
        <level val="81" hp="3433.0" mp="1281.6" cp="1888.15"/>
        <level val="82" hp="3497.98" mp="1307.25" cp="1923.889"/>
        <level val="83" hp="3563.34" mp="1333.05" cp="1959.837"/>
        <level val="84" hp="3629.08" mp="1359.0" cp="1995.994"/>
        <level val="85" hp="3695.2" mp="1385.1" cp="2032.36"/>
        <level val="86" hp="3761.7" mp="1411.35" cp="2068.935"/>
        <level val="87" hp="3828.58" mp="1437.75" cp="2105.719"/>
        <level val="88" hp="3895.84" mp="1464.3" cp="2142.712"/>
        <level val="89" hp="3963.48" mp="1491.0" cp="2179.914"/>
        <level val="90" hp="4031.5" mp="1517.85" cp="2217.325"/>
        <level val="91" hp="4099.9" mp="1544.85" cp="2254.945"/>
        <level val="92" hp="4168.68" mp="1572.0" cp="2292.774"/>
        <level val="93" hp="4237.84" mp="1599.3" cp="2330.812"/>
        <level val="94" hp="4307.38" mp="1626.75" cp="2369.059"/>
        <level val="95" hp="4377.3" mp="1654.35" cp="2407.515"/>
        <level val="96" hp="4447.6" mp="1682.1" cp="2446.18"/>
        <level val="97" hp="4518.28" mp="1710.0" cp="2485.054"/>
        <level val="98" hp="4589.34" mp="1738.05" cp="2524.137"/>
        <level val="99" hp="4660.78" mp="1766.25" cp="2563.429"/>
    </gain>
</list>
