=== GoldGamesTKD/Legacy-Interlude/gameserver/data/combination_item.dtd
<!ELEMENT list (combinationitem_begin)*>
<!ELEMENT combinationitem_begin (#PCDATA)>
<!ATTLIST combinationitem_begin
        chance CDATA #REQUIRED
        on_success CDATA #REQUIRED
        on_fail CDATA #REQUIRED
        slotone CDATA #REQUIRED
        slottwo CDATA #REQUIRED>

=== GoldGamesTKD/Legacy-Interlude/gameserver/data/combination_item.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "combination_item.dtd">

<list>
    <combinationitem_begin slotone="90311" slottwo="90311" chance="40" on_success="90312" on_fail="90311"/>
    <combinationitem_begin slotone="90313" slottwo="90313" chance="40" on_success="90314" on_fail="90313"/>
    <combinationitem_begin slotone="90314" slottwo="90314" chance="40" on_success="90315" on_fail="90314"/>
    <combinationitem_begin slotone="90315" slottwo="90315" chance="40" on_success="90316" on_fail="90315"/>
    <combinationitem_begin slotone="90316" slottwo="90316" chance="40" on_success="90317" on_fail="90316"/>
    <combinationitem_begin slotone="90318" slottwo="90318" chance="40" on_success="90319" on_fail="90318"/>
    <combinationitem_begin slotone="90319" slottwo="90319" chance="40" on_success="90320" on_fail="90319"/>
    <combinationitem_begin slotone="90320" slottwo="90320" chance="40" on_success="90321" on_fail="90320"/>
    <combinationitem_begin slotone="90321" slottwo="90321" chance="40" on_success="90322" on_fail="90321"/>
    <combinationitem_begin slotone="90323" slottwo="90323" chance="40" on_success="90324" on_fail="90323"/>
    <combinationitem_begin slotone="90324" slottwo="90324" chance="40" on_success="90325" on_fail="90324"/>
    <combinationitem_begin slotone="90325" slottwo="90325" chance="40" on_success="90326" on_fail="90325"/>
    <combinationitem_begin slotone="90326" slottwo="90326" chance="40" on_success="90327" on_fail="90326"/>
    <combinationitem_begin slotone="90328" slottwo="90328" chance="40" on_success="90329" on_fail="90328"/>
    <combinationitem_begin slotone="90329" slottwo="90329" chance="40" on_success="90330" on_fail="90329"/>
    <combinationitem_begin slotone="90330" slottwo="90330" chance="40" on_success="90331" on_fail="90330"/>
    <combinationitem_begin slotone="90331" slottwo="90331" chance="40" on_success="90332" on_fail="90331"/>
    <combinationitem_begin slotone="90333" slottwo="90333" chance="40" on_success="90334" on_fail="90333"/>
    <combinationitem_begin slotone="90334" slottwo="90334" chance="40" on_success="90335" on_fail="90334"/>
    <combinationitem_begin slotone="90335" slottwo="90335" chance="40" on_success="90336" on_fail="90335"/>
    <combinationitem_begin slotone="90336" slottwo="90336" chance="40" on_success="90337" on_fail="90336"/>
    <combinationitem_begin slotone="90338" slottwo="90338" chance="40" on_success="90339" on_fail="90338"/>
    <combinationitem_begin slotone="90339" slottwo="90339" chance="40" on_success="90340" on_fail="90339"/>
    <combinationitem_begin slotone="90340" slottwo="90340" chance="40" on_success="90341" on_fail="90340"/>
    <combinationitem_begin slotone="90341" slottwo="90341" chance="40" on_success="90342" on_fail="90341"/>
    <combinationitem_begin slotone="90343" slottwo="90343" chance="40" on_success="90344" on_fail="90343"/>
    <combinationitem_begin slotone="90344" slottwo="90344" chance="40" on_success="90345" on_fail="90344"/>
    <combinationitem_begin slotone="90345" slottwo="90345" chance="40" on_success="90346" on_fail="90345"/>
    <combinationitem_begin slotone="90346" slottwo="90346" chance="40" on_success="90347" on_fail="90346"/>
    <combinationitem_begin slotone="90353" slottwo="90353" chance="40" on_success="90354" on_fail="90353"/>
    <combinationitem_begin slotone="90354" slottwo="90354" chance="40" on_success="90355" on_fail="90354"/>
    <combinationitem_begin slotone="90355" slottwo="90355" chance="40" on_success="90356" on_fail="90355"/>
    <combinationitem_begin slotone="90356" slottwo="90356" chance="40" on_success="90357" on_fail="90356"/>
    <combinationitem_begin slotone="90534" slottwo="90534" chance="40" on_success="90535" on_fail="90534"/>
    <combinationitem_begin slotone="90535" slottwo="90534" chance="40" on_success="90536" on_fail="90534"/>
    <combinationitem_begin slotone="90536" slottwo="90534" chance="40" on_success="90537" on_fail="90534"/>
    <combinationitem_begin slotone="90537" slottwo="90534" chance="40" on_success="90538" on_fail="90534"/>
    <combinationitem_begin slotone="90538" slottwo="90534" chance="40" on_success="90539" on_fail="90537"/>
    <combinationitem_begin slotone="90539" slottwo="90534" chance="40" on_success="90540" on_fail="90537"/>
    <combinationitem_begin slotone="90540" slottwo="90534" chance="40" on_success="90541" on_fail="90537"/>
    <combinationitem_begin slotone="90541" slottwo="90534" chance="40" on_success="90542" on_fail="90537"/>
    <combinationitem_begin slotone="90542" slottwo="90534" chance="40" on_success="90543" on_fail="90537"/>
    <combinationitem_begin slotone="90543" slottwo="90534" chance="40" on_success="90544" on_fail="90542"/>
    <combinationitem_begin slotone="90544" slottwo="90534" chance="40" on_success="90545" on_fail="90542"/>
    <combinationitem_begin slotone="90545" slottwo="90534" chance="40" on_success="90546" on_fail="90542"/>
    <combinationitem_begin slotone="90546" slottwo="90534" chance="40" on_success="90547" on_fail="90542"/>
    <combinationitem_begin slotone="90547" slottwo="90534" chance="40" on_success="90548" on_fail="90542"/>
    <combinationitem_begin slotone="90548" slottwo="90534" chance="40" on_success="90549" on_fail="90534"/>
    <combinationitem_begin slotone="90549" slottwo="90534" chance="40" on_success="90550" on_fail="90534"/>
    <combinationitem_begin slotone="90550" slottwo="90534" chance="40" on_success="90551" on_fail="90534"/>
    <combinationitem_begin slotone="90551" slottwo="90534" chance="40" on_success="90552" on_fail="90534"/>
    <combinationitem_begin slotone="90552" slottwo="90534" chance="40" on_success="90553" on_fail="90534"/>
    <combinationitem_begin slotone="90554" slottwo="90554" chance="40" on_success="90555" on_fail="90554"/>
    <combinationitem_begin slotone="90555" slottwo="90554" chance="40" on_success="90556" on_fail="90554"/>
    <combinationitem_begin slotone="90556" slottwo="90554" chance="40" on_success="90557" on_fail="90554"/>
    <combinationitem_begin slotone="90557" slottwo="90554" chance="40" on_success="90558" on_fail="90554"/>
    <combinationitem_begin slotone="90558" slottwo="90554" chance="40" on_success="90559" on_fail="90557"/>
    <combinationitem_begin slotone="90559" slottwo="90554" chance="40" on_success="90560" on_fail="90557"/>
    <combinationitem_begin slotone="90560" slottwo="90554" chance="40" on_success="90561" on_fail="90557"/>
    <combinationitem_begin slotone="90561" slottwo="90554" chance="40" on_success="90562" on_fail="90557"/>
    <combinationitem_begin slotone="90562" slottwo="90554" chance="40" on_success="90563" on_fail="90557"/>
    <combinationitem_begin slotone="90563" slottwo="90554" chance="40" on_success="90564" on_fail="90562"/>
    <combinationitem_begin slotone="90564" slottwo="90554" chance="40" on_success="90565" on_fail="90562"/>
    <combinationitem_begin slotone="90565" slottwo="90554" chance="40" on_success="90566" on_fail="90562"/>
    <combinationitem_begin slotone="90566" slottwo="90554" chance="40" on_success="90567" on_fail="90562"/>
    <combinationitem_begin slotone="90567" slottwo="90554" chance="40" on_success="90568" on_fail="90562"/>
    <combinationitem_begin slotone="90568" slottwo="90554" chance="40" on_success="90569" on_fail="90554"/>
    <combinationitem_begin slotone="90569" slottwo="90554" chance="40" on_success="90570" on_fail="90554"/>
    <combinationitem_begin slotone="90570" slottwo="90554" chance="40" on_success="90571" on_fail="90554"/>
    <combinationitem_begin slotone="90571" slottwo="90554" chance="40" on_success="90572" on_fail="90554"/>
    <combinationitem_begin slotone="90572" slottwo="90554" chance="40" on_success="90573" on_fail="90554"/>
    <combinationitem_begin slotone="90574" slottwo="90574" chance="40" on_success="90575" on_fail="90574"/>
    <combinationitem_begin slotone="90575" slottwo="90574" chance="40" on_success="90576" on_fail="90574"/>
    <combinationitem_begin slotone="90576" slottwo="90574" chance="40" on_success="90577" on_fail="90574"/>
    <combinationitem_begin slotone="90577" slottwo="90574" chance="40" on_success="90578" on_fail="90574"/>
    <combinationitem_begin slotone="90578" slottwo="90574" chance="40" on_success="90579" on_fail="90577"/>
    <combinationitem_begin slotone="90579" slottwo="90574" chance="40" on_success="90580" on_fail="90577"/>
    <combinationitem_begin slotone="90580" slottwo="90574" chance="40" on_success="90581" on_fail="90577"/>
    <combinationitem_begin slotone="90581" slottwo="90574" chance="40" on_success="90582" on_fail="90577"/>
    <combinationitem_begin slotone="90582" slottwo="90574" chance="40" on_success="90583" on_fail="90577"/>
    <combinationitem_begin slotone="90583" slottwo="90574" chance="40" on_success="90584" on_fail="90582"/>
    <combinationitem_begin slotone="90584" slottwo="90574" chance="40" on_success="90585" on_fail="90582"/>
    <combinationitem_begin slotone="90585" slottwo="90574" chance="40" on_success="90586" on_fail="90582"/>
    <combinationitem_begin slotone="90586" slottwo="90574" chance="40" on_success="90587" on_fail="90582"/>
    <combinationitem_begin slotone="90587" slottwo="90574" chance="40" on_success="90588" on_fail="90582"/>
    <combinationitem_begin slotone="90588" slottwo="90574" chance="40" on_success="90589" on_fail="90574"/>
    <combinationitem_begin slotone="90589" slottwo="90574" chance="40" on_success="90590" on_fail="90574"/>
    <combinationitem_begin slotone="90590" slottwo="90574" chance="40" on_success="90591" on_fail="90574"/>
    <combinationitem_begin slotone="90591" slottwo="90574" chance="40" on_success="90592" on_fail="90574"/>
    <combinationitem_begin slotone="90592" slottwo="90574" chance="40" on_success="90593" on_fail="90574"/>
    <combinationitem_begin slotone="90594" slottwo="90594" chance="40" on_success="90595" on_fail="90594"/>
