=== GoldGamesTKD/Legacy-Interlude/gameserver/data/ensoul_options.dtd
<!ELEMENT list (ensoul_option)*>
<!ELEMENT ensoul_option (#PCDATA)>
<!ATTLIST ensoul_option
        id CDATA #REQUIRED
        skillId CDATA #REQUIRED
        skillLvl CDATA #REQUIRED
        optionType CDATA #REQUIRED
        slotType CDATA #REQUIRED
        stoneId CDATA #REQUIRED
        name CDATA #IMPLIED
        icon CDATA #IMPLIED>

=== GoldGamesTKD/Legacy-Interlude/gameserver/data/ensoul_options.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "ensoul_options.dtd">
<list>
    <ensoul_option id="1" stoneId="29818" skillId="55253" skillLvl="1" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- P. Def. +20.2 -->
    <ensoul_option id="2" stoneId="29819" skillId="55253" skillLvl="2" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- P. Def. +24.6 -->
    <ensoul_option id="3" stoneId="29820" skillId="55253" skillLvl="3" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- P. Def. +29.8 -->
    <ensoul_option id="4" stoneId="29821" skillId="55253" skillLvl="4" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- P. Def. +35.7 -->
    <ensoul_option id="5" stoneId="29822" skillId="55253" skillLvl="5" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- P. Def. +42.6 -->
    <ensoul_option id="6" stoneId="29823" skillId="55253" skillLvl="6" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- P. Def. +50.7 -->
    <ensoul_option id="7" stoneId="29824" skillId="55253" skillLvl="7" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- P. Def. +57.9 -->
    <ensoul_option id="8" stoneId="29825" skillId="55253" skillLvl="8" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- P. Def. +66.1 -->
    <ensoul_option id="9" stoneId="29826" skillId="55253" skillLvl="9" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- P. Def. +75.3 -->
    <ensoul_option id="10" stoneId="29827" skillId="55253" skillLvl="10" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- P. Def. +83.5 -->
    <ensoul_option id="11" stoneId="29828" skillId="55253" skillLvl="11" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- P. Def. +92.2 -->
    <ensoul_option id="12" stoneId="29829" skillId="55253" skillLvl="12" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- P. Def. +101.6 -->
    <ensoul_option id="13" stoneId="29830" skillId="55253" skillLvl="13" optionType="73" name="sigels_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- P. Def. +112.7 -->
    <ensoul_option id="14" stoneId="29831" skillId="55253" skillLvl="14" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="15" stoneId="29832" skillId="55253" skillLvl="15" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="16" stoneId="29833" skillId="55253" skillLvl="16" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="17" stoneId="29834" skillId="55253" skillLvl="17" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="18" stoneId="29835" skillId="55253" skillLvl="18" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="19" stoneId="29836" skillId="55253" skillLvl="19" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="20" stoneId="29837" skillId="55253" skillLvl="20" optionType="73" name="sigels_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- P. Def. +2 -->
    <ensoul_option id="21" stoneId="29818" skillId="55254" skillLvl="1" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- Max HP +73 -->
    <ensoul_option id="22" stoneId="29819" skillId="55254" skillLvl="2" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- Max HP +94 -->
    <ensoul_option id="23" stoneId="29820" skillId="55254" skillLvl="3" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- Max HP +129 -->
    <ensoul_option id="24" stoneId="29821" skillId="55254" skillLvl="4" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- Max HP +154 -->
    <ensoul_option id="25" stoneId="29822" skillId="55254" skillLvl="5" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv00"/> <!-- Max HP +185 -->
    <ensoul_option id="26" stoneId="29823" skillId="55254" skillLvl="6" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- Max HP +223 -->
    <ensoul_option id="27" stoneId="29824" skillId="55254" skillLvl="7" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- Max HP +249 -->
    <ensoul_option id="28" stoneId="29825" skillId="55254" skillLvl="8" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- Max HP +276 -->
    <ensoul_option id="29" stoneId="29826" skillId="55254" skillLvl="9" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- Max HP +303 -->
    <ensoul_option id="30" stoneId="29827" skillId="55254" skillLvl="10" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv01"/> <!-- Max HP +331 -->
    <ensoul_option id="31" stoneId="29828" skillId="55254" skillLvl="11" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- Max HP +359 -->
    <ensoul_option id="32" stoneId="29829" skillId="55254" skillLvl="12" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- Max HP +388 -->
    <ensoul_option id="33" stoneId="29830" skillId="55254" skillLvl="13" optionType="74" name="sigel_protection" slotType="1" icon="BranchIcon.Icon.g_rune_sigel_lv02"/> <!-- Max HP +418 -->
    <ensoul_option id="34" stoneId="29831" skillId="55254" skillLvl="14" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="35" stoneId="29832" skillId="55254" skillLvl="15" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="36" stoneId="29833" skillId="55254" skillLvl="16" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="37" stoneId="29834" skillId="55254" skillLvl="17" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="38" stoneId="29835" skillId="55254" skillLvl="18" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="39" stoneId="29836" skillId="55254" skillLvl="19" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="40" stoneId="29837" skillId="55254" skillLvl="20" optionType="74" name="sigel_protection" slotType="1" icon="icon.ensoul_big_p"/> <!-- Max HP +50 -->
    <ensoul_option id="41" stoneId="29838" skillId="55255" skillLvl="1" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv00" /> <!-- P. Atk. +2.8 -->
    <ensoul_option id="42" stoneId="29839" skillId="55255" skillLvl="2" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv00" /> <!-- P. Atk. +3.8 -->
    <ensoul_option id="43" stoneId="29840" skillId="55255" skillLvl="3" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv00" /> <!-- P. Atk. +5.1 -->
    <ensoul_option id="44" stoneId="29841" skillId="55255" skillLvl="4" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv00" /> <!-- P. Atk. +7.8 -->
    <ensoul_option id="45" stoneId="29842" skillId="55255" skillLvl="5" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv00" /> <!-- P. Atk. +10.1 -->
    <ensoul_option id="46" stoneId="29843" skillId="55255" skillLvl="6" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv01" /> <!-- P. Atk. +12.9 -->
    <ensoul_option id="47" stoneId="29844" skillId="55255" skillLvl="7" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv01" /> <!-- P. Atk. +15.3 -->
    <ensoul_option id="48" stoneId="29845" skillId="55255" skillLvl="8" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv01" /> <!-- P. Atk. +18.1 -->
    <ensoul_option id="49" stoneId="29846" skillId="55255" skillLvl="9" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv01" /> <!-- P. Atk. +21.2 -->
    <ensoul_option id="50" stoneId="29847" skillId="55255" skillLvl="10" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv01" /> <!-- P. Atk. +24.3 -->
    <ensoul_option id="51" stoneId="29848" skillId="55255" skillLvl="11" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv02" /> <!-- P. Atk. +28 -->
    <ensoul_option id="52" stoneId="29849" skillId="55255" skillLvl="12" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv02" /> <!-- P. Atk. +31.9 -->
    <ensoul_option id="53" stoneId="29850" skillId="55255" skillLvl="13" optionType="75" name="tyrr_might" slotType="1" icon="BranchIcon.Icon.g_rune_tir_lv02" /> <!-- P. Atk. +36.5 -->
