=== GoldGamesTKD/Legacy-Interlude/gameserver/data/purchase_limit_craft.dtd
<!ELEMENT list (item)*>
<!ELEMENT item (ingredient)*>
<!ATTLIST item
        shop_index CDATA #REQUIRED
        product_name CDATA #IMPLIED
        product_item CDATA #REQUIRED
        product_item_amount CDATA #IMPLIED
        product_item_chance CDATA #IMPLIED
        buy_item_1 CDATA #IMPLIED
        buy_item_amount_1 CDATA #IMPLIED
        buy_item_chance_1 CDATA #IMPLIED
        buy_item_2 CDATA #IMPLIED
        buy_item_amount_2 CDATA #IMPLIED
        buy_item_chance_2 CDATA #IMPLIED
        buy_item_3 CDATA #IMPLIED
        buy_item_amount_3 CDATA #IMPLIED
        buy_item_chance_3 CDATA #IMPLIED
        buy_item_4 CDATA #IMPLIED
        buy_item_amount_4 CDATA #IMPLIED
        buy_item_chance_4 CDATA #IMPLIED
        limit_daily CDATA #IMPLIED
        product_id CDATA #REQUIRED>
<!ELEMENT ingredient (#PCDATA)>
<!ATTLIST ingredient
        count CDATA #REQUIRED
        id CDATA #REQUIRED
        enchantLevel CDATA #IMPLIED>

=== GoldGamesTKD/Legacy-Interlude/gameserver/data/purchase_limit_craft.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "purchase_limit_craft.dtd">
<list>
    <item shop_index="4" product_id="10007" product_name="Feudal Islet" product_item="99286" product_item_amount="1"
          product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10008" product_name="Feudal Duty" product_item="99287" product_item_amount="1"
          product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10" buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10009" product_name="Silenos Priest's Staff" product_item="99288"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10010" product_name="Silenos Claw" product_item="99289" product_item_amount="1"
          product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10" buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10011" product_name="Ketra Orc's Battle Axe" product_item="99290"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10012" product_name="Orc Commander's Polearm" product_item="99291"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10013" product_name="Dragon Bone Blade" product_item="99292"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10014" product_name="Dragon Piercer" product_item="99293" product_item_amount="1"
          product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10" buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10015" product_name="Maluk Berserker Blade" product_item="99294"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10016" product_name="Antharas Follower's Staff" product_item="99295"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10017" product_name="Guardian's Spear" product_item="99296" product_item_amount="1"
          product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10" buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10018" product_name="Greatsword of Judgment" product_item="99297"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10019" product_name="Rapier of Insolence" product_item="99298"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="90907" buy_item_amount_1="10"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10001" product_name="Elixir" product_item="94314" product_item_amount="1"
          product_item_chance="5.0" buy_item_1="94328" buy_item_amount_1="7" buy_item_chance_1="95.0">
        <ingredient id="91663" count="10000"/>
    </item>
	<!-- TODO: Add remaining items
    <item shop_index="4" product_id="10020" product_name="Transformation Sealbook: Ninja Assassin" product_item="91272"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91262" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10021" product_name="Transformation Sealbook: Blue Musketeer" product_item="91275"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91265" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10022" product_name="Transformation Sealbook: Valkyrie"
          product_item="91279" product_item_amount="1" product_item_chance="30.0" buy_item_1="91269"
          buy_item_amount_1="25" buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10023" product_name="Transformation Sealbook: Wild Wolf"
          product_item="91278" product_item_amount="1" product_item_chance="30.0" buy_item_1="91268"
          buy_item_amount_1="25" buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10024" product_name="Transformation Sealbook: Caravan"
          product_item="91280" product_item_amount="1" product_item_chance="30.0" buy_item_1="91270"
          buy_item_amount_1="25" buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10025" product_name="Transformation Sealbook: Purple Cowboy" product_item="91276"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91266" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10026" product_name="Transformation Sealbook: High Priest" product_item="91277"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91267" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10027" product_name="Transformation Sealbook: Blood Noblesse" product_item="91273"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91263" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10028" product_name="Transformation Sealbook: White Noblesse" product_item="91274"
          product_item_amount="1" product_item_chance="30.0" buy_item_1="91264" buy_item_amount_1="25"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10029" product_name="Transformation Sealbook: Dragon Berserker"
          product_item="91281" product_item_amount="1" product_item_chance="30.0" buy_item_1="91271"
          buy_item_amount_1="56"
          buy_item_chance_1="70.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10030" product_name="17th Anniversary Maestro Box" product_item="95633"
          product_item_amount="1" product_item_chance="10.0" buy_item_1="99340" buy_item_amount_1="1"
          buy_item_chance_1="90.0">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10031" product_name="Freeze Breastplate Pack" product_item="93797"
          product_item_amount="1" product_item_chance="0.5"
          buy_item_1="93841" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>    
    <item shop_index="4" product_id="10032" product_name="Freeze Gaiters Pack" product_item="93798"
          product_item_amount="1" product_item_chance="0.5"
          buy_item_1="93842" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>    
    <item shop_index="4" product_id="10033" product_name="Thunder Leather Armor Pack" product_item="93795"
          product_item_amount="1" product_item_chance="0.5"
          buy_item_1="93839" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10034" product_name="Thunder Leather Leggings Pack" product_item="93796"
          product_item_amount="1" product_item_chance="0.05"
          buy_item_1="93840" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10035" product_name="Flaming Tunic Pack" product_item="93799"
          product_item_amount="1" product_item_chance="0.05"
          buy_item_1="93843" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>
    <item shop_index="4" product_id="10036" product_name="Flaming Stockings Pack" product_item="93800"
          product_item_amount="1" product_item_chance="0.05"
          buy_item_1="93844" buy_item_amount_1="1" buy_item_chance_1="4.5"
          buy_item_2="92314" buy_item_amount_2="19" buy_item_chance_2="95.45">
        <ingredient id="91663" count="10000"/>
    </item>
